# Site settings
title: "The Intergalactic Railroad"
email: igrr@protonmail.com
description: "Notes on the Independent Space Programs"
baseurl: ""
url: "http://intergalactirailroad.github.io"
title_description: "A Depiction of the Independent Space Programs of the Planet Earth in the year 02017"
title_image: "/images/littlemoon.png"
google_analytics: 
disqus_account: 
github_repository: https://intergalacticrailroad.github.io/
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: ars_vuca
github_username:  intergalacticrailroad
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
#footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
#footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
